export const REQUEST_FETCH_IN_PROGRESS_OTTP = 'REQUEST_FETCH_IN_PROGRESS_OTTP'
export const SUCCESS_FETCH_IN_PROGRESS_OTTP = 'SUCCESS_FETCH_IN_PROGRESS_OTTP'

export const REQUEST_FETCH_HISTORY_OTTP = 'REQUEST_FETCH_HISTORY_OTTP'
export const SUCCESS_FETCH_HISTORY_OTTP = 'SUCCESS_FETCH_HISTORY_OTTP'

export const REQUEST_FETCH_OTTP_DETAIL = 'REQUEST_FETCH_OTTP_DETAIL'
export const SUCCESS_FETCH_OTTP_DETAIL = 'SUCCESS_FETCH_OTTP_DETAIL'

export const REQUEST_SET_LOADING = 'REQUEST_SET_LOADING'
export const SUCCESS_SET_LOADING = 'SUCCESS_SET_LOADING'

export const REQUEST_SET_LOADING_ALL = 'REQUEST_SET_LOADING_ALL'
export const SUCCESS_SET_LOADING_ALL = 'SUCCESS_SET_LOADING_ALL'

export const REQUEST_UPDATE_STATE_EXCISE_RULES = 'REQUEST_UPDATE_STATE_EXCISE_RULES'
export const SUCCESS_UPDATE_STATE_EXCISE_RULES = 'SUCCESS_UPDATE_STATE_EXCISE_RULES'

export const REQUEST_FETCH_DSO_DETAILS = 'REQUEST_FETCH_DSO_DETAILS'
export const SUCCESS_FETCH_DSO_DETAILS = 'SUCCESS_FETCH_DSO_DETAILS'

export const REQUEST_FETCH_DSO_LIST = 'REQUEST_FETCH_DSO_LIST'
export const SUCCESS_FETCH_DSO_LIST = 'SUCCESS_FETCH_DSO_LIST'

export const REQUEST_FETCH_RETAILER_DETAILS = 'REQUEST_FETCH_RETAILER_DETAILS'
export const SUCCESS_FETCH_RETAILER_DETAILS = 'SUCCESS_FETCH_RETAILER_DETAILS'

export const REQUEST_FETCH_RETAILER_LIST = 'REQUEST_FETCH_RETAILER_LIST'
export const SUCCESS_FETCH_RETAILER_LIST = 'SUCCESS_FETCH_RETAILER_LIST'

export const REQUEST_FETCH_RULES = 'REQUEST_FETCH_RULES'
export const SUCCESS_FETCH_RULES = 'SUCCESS_FETCH_RULES'

export const REQUEST_FETCH_CONSUMER_LIST = 'REQUEST_FETCH_CONSUMER_LIST'
export const SUCCESS_FETCH_CONSUMER_LIST = 'SUCCESS_FETCH_CONSUMER_LIST'

export const REQUEST_FETCH_CONSUMER_COMPLAINTS_LIST = 'REQUEST_FETCH_CONSUMER_COMPLAINTS_LIST'
export const SUCCESS_FETCH_CONSUMER_COMPLAINTS_LIST = 'SUCCESS_FETCH_CONSUMER_COMPLAINTS_LIST'

export const REQUEST_FETCH_CITIES_LIST = 'REQUEST_FETCH_CITIES_LIST'
export const SUCCESS_FETCH_CITIES_LIST = 'SUCCESS_FETCH_CITIES_LIST'

export const REQUEST_FETCH_OUTLETS_LIST = 'REQUEST_FETCH_OUTLETS_LIST'
export const SUCCESS_FETCH_OUTLETS_LIST = 'SUCCESS_FETCH_OUTLETS_LIST'