export const REQUEST_FETCH_IN_PROGRESS_OTTP = 'REQUEST_FETCH_IN_PROGRESS_OTTP'
export const SUCCESS_FETCH_IN_PROGRESS_OTTP = 'SUCCESS_FETCH_IN_PROGRESS_OTTP'

export const REQUEST_FETCH_HISTORY_OTTP = 'REQUEST_FETCH_HISTORY_OTTP'
export const SUCCESS_FETCH_HISTORY_OTTP = 'SUCCESS_FETCH_HISTORY_OTTP'

export const REQUEST_FETCH_OTTP_DETAIL = 'REQUEST_FETCH_OTTP_DETAIL'
export const SUCCESS_FETCH_OTTP_DETAIL = 'SUCCESS_FETCH_OTTP_DETAIL'

export const REQUEST_FETCH_SQUAD_MEMBERS = 'REQUEST_FETCH_SQUAD_MEMBERS'
export const SUCCESS_FETCH_SQUAD_MEMBERS = 'SUCCESS_FETCH_SQUAD_MEMBERS'

export const REQUEST_UPDATE_SQUAD_MEMBER = 'REQUEST_UPDATE_SQUAD_MEMBER'
export const SUCCESS_UPDATE_SQUAD_MEMBER = 'SUCCESS_UPDATE_SQUAD_MEMBER'

export const REQUEST_ADD_SQUAD_MEMBER = 'REQUEST_ADD_SQUAD_MEMBER'
export const SUCCESS_ADD_SQUAD_MEMBER = 'SUCCESS_ADD_SQUAD_MEMBER'

export const REQUEST_SET_LOADING = 'REQUEST_SET_LOADING'
export const SUCCESS_SET_LOADING = 'SUCCESS_SET_LOADING'

export const REQUEST_SET_LOADING_ALL = 'REQUEST_SET_LOADING_ALL'
export const SUCCESS_SET_LOADING_ALL = 'SUCCESS_SET_LOADING_ALL'
