export const REQUEST_ASSIGN_ORDER = 'REQUEST_ASSIGN_ORDER'
export const SUCCESS_ASSIGN_ORDER = 'SUCCESS_ASSIGN_ORDER'

export const REQUEST_FETCH_ORDERS_DATA = 'REQUEST_FETCH_ORDERS_DATA'
export const SUCCESS_FETCH_ORDERS_DATA = 'SUCCESS_FETCH_ORDERS_DATA'

export const REQUEST_FETCH_LIVE_ORDERS = 'REQUEST_FETCH_LIVE_ORDERS'
export const SUCCESS_FETCH_LIVE_ORDERS = 'SUCCESS_FETCH_LIVE_ORDERS'

export const REQUEST_FETCH_LIVE_ASSIGNED_ORDERS = 'REQUEST_FETCH_LIVE_ASSIGNED_ORDERS'
export const SUCCESS_FETCH_LIVE_ASSIGNED_ORDERS = 'SUCCESS_FETCH_LIVE_ASSIGNED_ORDERS'

export const REQUEST_FETCH_LIVE_UNASSIGNED_ORDERS = 'REQUEST_FETCH_LIVE_UNASSIGNED_ORDERS'
export const SUCCESS_FETCH_LIVE_UNASSIGNED_ORDERS = 'SUCCESS_FETCH_LIVE_UNASSIGNED_ORDERS'

export const REQUEST_FETCH_HISTORY_ORDERS = 'REQUEST_FETCH_HISTORY_ORDERS'
export const SUCCESS_FETCH_HISTORY_ORDERS = 'SUCCESS_FETCH_HISTORY_ORDERS'

export const REQUEST_FETCH_NEED_TO_BE_CANCELLED_ORDERS = 'REQUEST_FETCH_NEED_TO_BE_CANCELLED_ORDERS'
export const SUCCESS_FETCH_NEED_TO_BE_CANCELLED_ORDERS = 'SUCCESS_FETCH_NEED_TO_BE_CANCELLED_ORDERS'

export const REQUEST_FETCH_ATTEMPTED_ORDERS = 'REQUEST_FETCH_ATTEMPTED_ORDERS'
export const SUCCESS_FETCH_ATTEMPTED_ORDERS = 'SUCCESS_FETCH_ATTEMPTED_ORDERS'

export const REQUEST_FETCH_UNAVAILABLE_DP = 'REQUEST_FETCH_UNAVAILABLE_DP'
export const SUCCESS_FETCH_UNAVAILABLE_DP = 'SUCCESS_FETCH_UNAVAILABLE_DP'

export const REQUEST_FETCH_RETURNING_ORDERS = 'REQUEST_FETCH_RETURNING_ORDERS'
export const SUCCESS_FETCH_RETURNING_ORDERS = 'SUCCESS_FETCH_RETURNING_ORDERS'

export const REQUEST_RESTOCK_ORDER = 'REQUEST_RESTOCK_ORDER'
export const SUCCESS_RESTOCK_ORDER = 'SUCCESS_RESTOCK_ORDER'

export const REQUEST_SEARCH_LIVE_ORDERS = 'REQUEST_SEARCH_LIVE_ORDERS'
export const SUCCESS_SEARCH_LIVE_ORDERS = 'SUCCESS_SEARCH_LIVE_ORDERS'

export const REQUEST_SEARCH_LIVE_ASSIGNED_ORDERS = 'REQUEST_SEARCH_LIVE_ASSIGNED_ORDERS'
export const SUCCESS_SEARCH_LIVE_ASSIGNED_ORDERS = 'SUCCESS_SEARCH_LIVE_ASSIGNED_ORDERS'

export const REQUEST_SEARCH_LIVE_UNASSIGNED_ORDERS = 'REQUEST_SEARCH_LIVE_UNASSIGNED_ORDERS'
export const SUCCESS_SEARCH_LIVE_UNASSIGNED_ORDERS = 'SUCCESS_SEARCH_LIVE_UNASSIGNED_ORDERS'

export const REQUEST_SEARCH_HISTORY_ORDERS = 'REQUEST_SEARCH_HISTORY_ORDERS'
export const SUCCESS_SEARCH_HISTORY_ORDERS = 'SUCCESS_SEARCH_HISTORY_ORDERS'

export const REQUEST_FETCH_ORDER_DETAIL = 'REQUEST_FETCH_ORDER_DETAIL'
export const SUCCESS_FETCH_ORDER_DETAIL = 'SUCCESS_FETCH_ORDER_DETAIL'

export const REQUEST_FILTER_ORDERS_DATA = 'REQUEST_FILTER_ORDERS_DATA'
export const SUCCESS_FILTER_ORDERS_DATA = 'SUCCESS_FILTER_ORDERS_DATA'

export const REQUEST_FORCE_REDEEM = 'REQUEST_FORCE_REDEEM'
export const SUCCESS_FORCE_REDEEM = 'SUCCESS_FORCE_REDEEM'

export const REQUEST_SKIP_RETAILER = 'REQUEST_SKIP_RETAILER'
export const SUCCESS_SKIP_RETAILER = 'SUCCESS_SKIP_RETAILER'

export const REQUEST_SKIP_DELIVERER = 'REQUEST_SKIP_DELIVERER'
export const SUCCESS_SKIP_DELIVERER = 'SUCCESS_SKIP_DELIVERER'

export const REQUEST_CANCEL_ORDER = 'REQUEST_CANCEL_ORDER'
export const SUCCESS_CANCEL_ORDER = 'SUCCESS_CANCEL_ORDER'

export const REQUEST_SET_LOADING = 'REQUEST_SET_LOADING'
export const SUCCESS_SET_LOADING = 'SUCCESS_SET_LOADING'

export const REQUEST_CONFIRM_RETAILER = 'REQUEST_CONFIRM_RETAILER'
export const SUCCESS_CONFIRM_RETAILER = 'SUCCESS_CONFIRM_RETAILER'

export const REQUEST_CONFIRM_DELIVERER = 'REQUEST_CONFIRM_DELIVERER'
export const SUCCESS_CONFIRM_DELIVERER = 'SUCCESS_CONFIRM_DELIVERER'

export const REQUEST_AUTO_PILOT = 'REQUEST_AUTO_PILOT'
export const SUCCESS_AUTO_PILOT = 'SUCCESS_AUTO_PILOT'

export const REQUEST_FETCH_AUTO_PILOT_STATUS = 'REQUEST_FETCH_AUTO_PILOT_STATUS'
export const SUCCESS_FETCH_AUTO_PILOT_STATUS = 'SUCCESS_FETCH_AUTO_PILOT_STATUS'

export const REQUEST_FETCH_PLOT_DATA = 'REQUEST_FETCH_PLOT_DATA'
export const SUCCESS_FETCH_PLOT_DATA = 'SUCCESS_FETCH_PLOT_DATA'

export const REQUEST_FETCH_GENRES = 'REQUEST_FETCH_GENRES'
export const SUCCESS_FETCH_GENRES = 'SUCCESS_FETCH_GENRES'

export const REQUEST_DELETE_ITEM_FROM_CART = 'REQUEST_DELETE_ITEM_FROM_CART'
export const SUCCESS_DELETE_ITEM_FROM_CART = 'SUCCESS_DELETE_ITEM_FROM_CART'

export const REQUEST_ADD_ITEM_TO_CART = 'REQUEST_ADD_ITEM_TO_CART'
export const SUCCESS_ADD_ITEM_TO_CART = 'SUCCESS_ADD_ITEM_TO_CART'

export const REQUEST_ASSIGN_NEW_RETAILER_TO_ORDER = 'REQUEST_ASSIGN_NEW_RETAILER_TO_ORDER'
export const SUCCESS_ASSIGN_NEW_RETAILER_TO_ORDER = 'SUCCESS_ASSIGN_NEW_RETAILER_TO_ORDER'

export const REQUEST_ASSIGN_NEW_DP_TO_ORDER = 'REQUEST_ASSIGN_NEW_DP_TO_ORDER'
export const SUCCESS_ASSIGN_NEW_DP_TO_ORDER = 'SUCCESS_ASSIGN_NEW_DP_TO_ORDER'

export const REQUEST_CREATE_NOTE = 'REQUEST_CREATE_NOTE'
export const REQUEST_FETCH_NOTES = 'REQUEST_FETCH_NOTES'
export const SUCCESS_FETCH_NOTES = 'SUCCESS_FETCH_NOTES'

export const REQUEST_SET_LOADING_ALL = 'REQUEST_SET_LOADING_ALL'
export const SUCCESS_SET_LOADING_ALL = 'SUCCESS_SET_LOADING_ALL'
